apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: demo
  data:
    - secretKey: username
      remoteRef:
        key: mongo
        property: username
    - secretKey: password
      remoteRef:
        key: mongo
        property: password